#include <kernel/framebuffer.hpp>
#include <stdio.h>

extern "C" void kernel_main(void) {
    // clrscr();
    FBuf fb;
    fb.terminal_initialize();
    fb.terminal_putchar('A');
    fb.terminal_putchar('S');
    fb.terminal_putchar('X');
    fb.terminal_putchar('D');
    fb.terminal_putchar('M');
    fb.terminal_putchar('r');
    // fb.terminal_putchar('Z');
    fb.terminal_putchar('H');
    fb.terminal_putchar('W');
    fb.terminal_writestring(
        " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed "
        "vehicula vehicula tincidunt. Aenean venenatis leo id est facilisis "
        "blandit. Cras a risus ante. Nunc ultrices gravida scelerisque. Aenean "
        "pharetra facilisis interdum. Quisque eu tristique arcu. Suspendisse "
        "potenti. Ut facilisis elit tellus, in egestas dui efficitur id. Ut "
        "nec blandit metus. Aliquam sed lorem eu urna fermentum congue. Aenean "
        "sem enim, rutrum sit amet pellentesque quis, ullamcorper vel elit. "
        "Aenean malesuada velit sem, nec ultrices orci tincidunt ac. Ut at  $"
        "viverra metus. Nulla facilisi. Quisque tincidunt congue ornare. "
        "Aenean a tellus sapien. Fusce luctus nec diam vel hendrerit. Sed in "
        "sem convallis, finibus odio a, sodales nulla. Etiam condimentum urna "
        "sed arcu sodales, at finibus risus congue. Sed vulputate in felis a "
        "feugiat. Cras nec purus et neque porta sodales. Nam in libero ipsum. "
        "Morbi ac lobortis dolor. Nullam sollicitudin metus sit amet magna "
        "viverra, et congue tellus commodo. Sed porttitor faucibus eros, "
        "mattis pulvinar purus. Nunc condimentum dictum arcu. Quisque "
        "facilisis, libero sed lobortis molestie, velit diam commodo lectus, "
        "ac accumsan nisi velit at augue. Praesent rhoncus mi non ante "
        "eleifend placerat. Sed fringilla pretium massa quis pellentesque. "
        "Donec hendrerit lectus vitae erat blandit faucibus. Vivamus facilisis "
        "convallis sem quis ornare. Cras iaculis vitae massa at consequat. Nam "
        "in sollicitudin quam. Duis vel ultrices odio. Quisque finibus sapien "
        "id metus gravida, nec pulvinar ligula vestibulum. Aliquam elit mi, "
        "faucibus eu sollicitudin maximus, vestibulum sit amet diam. Etiam "
        "quis convallis arcu. Nulla ac porttitor ante. Fusce id leo faucibus, "
        "vestibulum eros tempor, lobortis felis. Morbi at viverra tellus. "
        "Integer eleifend, arcu ac maximus congue, orci purus gravida lorem, "
        "nec consectetur nunc diam sed justo. Pellentesque at magna nec metus "
        "maximus porta. Sed suscipit dapibus est vitae finibus. Proin sed "
        "pellentesque lacus. Curabitur risus eros, ultrices a felis tincidunt, "
        "maximus placerat velit. Sed ac pulvinar dui, sit amet malesuada "
        "risus. Quisque ac ante vitae lectus dignissim viverra. In porttitor "
        "non sapien vel tempus. Fusce ligula eros, sodales sed nunc porta, "
        "aliquam vulputate leo. Vestibulum at tincidunt enim. Maecenas tempor "
        "erat id interdum interdum. Nunc non iaculis tortor, in dignissim "
        "libero. Fusce volutpat enim quis sem vulputate, eget fermentum turpis "
        "facilisis. Fusce congue interdum dui. Maecenas aliquet pulvinar elit "
        "vitae dignissim. Fusce non odio at lectus sagittis lobortis sit amet "
        "nec nulla. Proin ac lacus massa. Aliquam dapibus quam at lacinia "
        "ultricies. Ut consequat eros nec placerat sagittis. Duis malesuada "
        "metus quis lacus egestas, sed facilisis sapien sodales. Curabitur "
        "mattis porta neque. Donec tempus volutpat suscipit. Duis sollicitudin "
        "diam vel convallis vehicula. Maecenas condimentum libero ut vulputate "
        "bibendum. Nulla bibendum nibh urna, non hendrerit lectus cursus sit "
        "amet. In sit amet elit eu ligula pretium commodo. Donec hendrerit "
        "turpis nec lectus cursus efficitur. Integer a faucibus justo. Integer "
        "vestibulum interdum nulla, eu consectetur sapien iaculis in. Aliquam "
        "suscipit lorem sit amet felis vestibulum, quis feugiat odio vehicula. "
        "Cras at arcu rhoncus, imperdiet augue sed, porttitor tortor. Donec "
        "vehicula diam vitae pharetra suscipit. Aliquam ullamcorper lacus eget "
        "imperdiet rhoncus. Cras rhoncus venenatis volutpat. Mauris euismod "
        "eros at volutpat mollis. Morbi consectetur ultricies pharetra. Cras "
        "tempor eros a ante commodo auctor. Fusce vel dui nec justo blandit "
        "accumsan. Praesent lobortis orci tempor vulputate finibus. Aenean "
        "vitae iaculis est. Proin ut felis mi. Aliquam non ex vel nibh "
        "efficitur fringilla. Nunc libero est, faucibus sed arcu non, porta "
        "aliquet sem. Curabitur fringilla, risus ac pretium eleifend, nisl "
        "urna pretium libero, nec auctor nisl velit sit amet nisl. Class "
        "aptent taciti sociosqu ad litora torquent per conubia nostra, per "
        "inceptos himenaeos. Proin tristique feugiat risus. Praesent egestas "
        "tincidunt ipsum et luctus. Sed quis ipsum nibh. Nam finibus egestas "
        "iaculis. Mauris ut justo vehicula, sodales mauris ac, scelerisque "
        "velit. Praesent ultricies feugiat tortor luctus rutrum. Donec sed "
        "elit nec nulla pulvinar consectetur at sit amet nunc. Praesent nibh "
        "ante, euismod faucibus augue id, bibendum tempor augue. Nunc "
        "tincidunt sollicitudin accumsan. Etiam fermentum hendrerit tempor. "
        "Vivamus accumsan ultricies euismod. Suspendisse potenti. Aenean "
        "tempor velit rutrum nulla eleifend sollicitudin. Donec hendrerit "
        "pharetra magna a aliquet. Nam augue enim, pellentesque ut placerat "
        "sit amet, tempor dignissim augue. Fusce consectetur magna vitae "
        "facilisis ornare. Cras blandit ante et nisi lobortis efficitur. "
        "Nullam finibus mauris augue, condimentum semper metus convallis eu. "
        "Etiam sollicitudin, nisi dignissim rhoncus sollicitudin, ipsum libero "
        "tempor elit, aliquet sagittis nisi diam ut felis. Vivamus luctus "
        "commodo elementum. In hac habitasse platea dictumst. In eu imperdiet "
        "felis, ac scelerisque lorem. Quisque quis lectus a turpis bibendum "
        "aliquet a eget nibh. In hac habitasse platea dictumst. Suspendisse "
        "sit amet augue magna. In non consequat urna. Sed gravida lorem vitae "
        "est ullamcorper, vehicula interdum nisl feugiat. Maecenas feugiat ex "
        "in ex mattis, a mollis ex euismod. Proin eget ligula eget est "
        "lobortis efficitur auctor in odio. Nam gravida auctor velit, sit amet "
        "auctor nisl maximus at. Pellentesque aliquet facilisis ligula vel "
        "volutpat. Maecenas urna ligula, efficitur ac nisi ut, pharetra "
        "sagittis dolor. Nullam eu tellus ut lectus tristique imperdiet in at "
        "libero. Cras pulvinar mattis dui at dignissim. Nam accumsan ligula at "
        "lacus commodo consectetur. Integer elementum est quis dictum luctus. "
        "Nullam ac pretium ante. Pellentesque a elit in nulla ullamcorper "
        "facilisis. Sed sollicitudin nulla sit amet consectetur finibus. Sed "
        "ullamcorper aliquet felis et ullamcorper. Curabitur ultrices congue "
        "magna quis ornare. Maecenas placerat quam eget purus tincidunt, in "
        "laoreet libero dapibus. Donec feugiat ut lorem ac porta. Pellentes#ue "
        "eros tortor, eleifend eu erat ut, dictum laoreet neque. Pellentesque "
        "dignissim neque dui. Pellentesque commodo consectetur urna ac mollis. "
        "Phasellus interdum auctor diam, et condimentum dui tristique in. "
        "Pellentesque dictum suscipit faucibus. In eu hendrerit nibh. Nulla "
        "malesuada massa eget ligula viverra auctor. Aenean non enim rhoncus, "
        "digni\tim\t mauri\ns ac, tincidunt justo. In erat felis, ultrices sit "
        "amet convallis et, faucibus vel ligula. Morbi metus lectus, tempor "
        "nec maximus a, fermentum et orci. Mauris vitae eros in urna tincidunt "
        "varius non id est. Sed venenatis massa neque, sodales ullamcorper "
        "nunc rutrum nec. Duis ac bibendum magna, eget ornare lacus. Ut "
        "finibus urna eu dolor gravida rutu\0"
        // Here first page
        "rum. Vivamus quis est eget lacus "
        "elementum interdum. Pellentesque semper lectus vitae quam fermentum, "
        "ac auctor ante eleifend. Fusce quis nunc elit. Nunc at nisl id enim "
        "ullamcorper hendrerit. Duis posuere est nisi, gravida pellentesque "
        "turpis condimentum nec. Suspendisse a nisi imperdiet, lobortis dui "
        "eu, tempus nunc. Etiam et lectus magna. Nam mattis, lacus in "
        "malesuada lacinia, nulla quam sagittis ligula, eleifend aliquet quam "
        "risus eget lectus. Cras aliquam scelerisque tristique. Nulla sit amet "
        "felis leo. Cras non dui nulla. Maecenas cursus nec tortor aliquam "
        "imperdiet. Phasellus ex dolor, varius vitae convallis nec, fermentum "
        "et nisi. Mauris pulvinar dapibus neque quis molestie. Integer "
        "pulvinar eros nisl, id rutrum ipsum venenatis vitae. Nam a suscipit "
        "diam, ac consequat augue. Integer fermentum lectus lacus, non "
        "malesuada nunc malesuada quis. Suspendisse potenti. Mauris eget "
        "mauris blandit, aliquet dui in, varius diam. Quisque iaculis semper "
        "neque non ultrices. Proin a arcu a dui accumsan vulputate. Cras "
        "aliquam dui vel ipsum dignissim, quis fermentum magna pharetra. Nunc "
        "viverra mauris placerat, convallis eros quis, mollis lectus. Ut "
        "tempor feugiat ipsum, a pulvinar libero molestie at. Etiam euismod "
        "vel nibh a vulputate. Aliquam erat volutpat. Praesent imperdiet "
        "dictum mauris, sed condimentum nisl tristique id. Nunc non quam in "
        "nisi consectetur dignissim id ac odio. Sed finibus tempor fermentum. "
        "Integer leo augue, vehicula vel eleifend non, viverra sed felis. In "
        "ac leo auctor, pretium nulla eget, elementum sapien. Nulla augue "
        "metus, vestibulum vitae aliquet sed, lobortis sed sem. Aliquam "
        "pretium sollicitudin arcu sed viverra. Pellentesque eget lectus vel "
        "lectus elementum fermentum. Integer sit amet cursus mi. Donec at "
        "luctus quam. Duis egestas pretium nisl vitae aliquam. Vivamus dictum, "
        "nibh eget bibendum efficitur, neque nisl dictum est, eu euismod nunc "
        "dui at ipsum. Integer varius sed metus eget eleifend. Quisque eu "
        "dapibus magna. Praesent ultrices, nulla nec facilisis pulvinar, lacus "
        "mi luctus ipsum, eget luctus mauris sem eget odio. In blandit, elit "
        "vel fermentum ultrices, risus augue vulputate ante, vitae luctus urna "
        "tellus ut felis. Nulla posuere tellus ac dui venenatis fringilla. "
        "Fusce egestas velit at placerat fringilla. Maecenas dignissim amet.");
    // printf("Hello, kernel World!\n");
}
